export default function TermsOfService() {
  return (
    <div className="container mx-auto px-4 py-16 max-w-4xl">
      <h1 className="text-4xl font-bold mb-8 font-display text-foreground">Terms of Service</h1>
      <div className="prose prose-slate dark:prose-invert max-w-none space-y-6 text-muted-foreground">
        <section>
          <h2 className="text-2xl font-semibold text-foreground mb-4">Agreement to Terms</h2>
          <p>By accessing or using MedScope AI, you agree to be bound by these Terms of Service. If you do not agree to all of these terms, do not use our services.</p>
        </section>
        <section>
          <h2 className="text-2xl font-semibold text-foreground mb-4">No Medical Advice</h2>
          <p className="font-bold text-destructive">MedScope AI IS FOR INFORMATIONAL PURPOSES ONLY. IT DOES NOT PROVIDE MEDICAL DIAGNOSES, ADVICE, OR TREATMENT. ALWAYS SEEK THE ADVICE OF YOUR PHYSICIAN OR OTHER QUALIFIED HEALTH PROVIDER.</p>
        </section>
        <section>
          <h2 className="text-2xl font-semibold text-foreground mb-4">User Responsibilities</h2>
          <p>You are responsible for the information you provide and how you use the insights generated by our AI. You must be at least 18 years old to use this service independently.</p>
        </section>
        <section>
          <h2 className="text-2xl font-semibold text-foreground mb-4">Limitation of Liability</h2>
          <p>Champions Crew and MedScope AI shall not be liable for any damages resulting from the use or inability to use our informational tools.</p>
        </section>
      </div>
    </div>
  );
}
